global:
  resolve_timeout: 5m
  slack_api_url_file: /run/secrets/slack_webhook

route:
  receiver: slack
  group_by: [alertname]
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 4h

receivers:
  - name: slack
    slack_configs:
      - send_resolved: true
