services:
  postgres:
    image: postgres:18.1
    volumes:
      - db_postgres:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stocks
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d stocks"]
      interval: 5s
      timeout: 5s
      retries: 10

  keycloak-postgres:
    image: postgres:18.1
    volumes:
      - keycloak_postgres:/var/lib/postgresql
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak"]
      interval: 5s
      timeout: 5s
      retries: 10

  keycloak:
    image: keycloak/keycloak:26.6
    command:
      - start-dev
      - --import-realm
    ports:
      - "7777:7777"
      - "9000:9000"
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import:ro
    environment:
      KC_HTTP_PORT: 7777
      KC_HOSTNAME: http://localhost:7777
      KC_HOSTNAME_ADMIN: http://localhost:7777

      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak

      KC_HTTP_RELATIVE_PATH: /
      KC_HTTP_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"

    depends_on:
      keycloak-postgres:
        condition: service_healthy

  prometheus:
    image: prom/prometheus
    container_name: observability-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: observability-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
volumes:
  db_postgres:
  keycloak_postgres:
  prometheus_data:
  grafana_data: