server:
  port: ${PORT:8080}

logging:
  level:
    org:
      atmosphere: warn

vaadin:
  launch-browser: false
  allowed-packages: com.vaadin,org.vaadin,com.flowingcode,com.wornux

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: inventory-management
            client-secret: ${KEYCLOAK_CLIENT_SECRET:}
            authorization-grant-type: authorization_code
            scope: openid,profile
        provider:
          keycloak:
            issuer-uri: http://localhost:7777/realms/wornux
            user-name-attribute: preferred_username
  datasource:
    url: jdbc:postgresql://localhost:5432/stocks
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      org:
        hibernate:
          envers:
            audit_table_suffix: _log
            store_data_at_delete: true
  flyway:
    enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
