create table role (
    id bigint generated by default as identity primary key,
    code varchar(80) not null unique,
    name varchar(120) not null,
    description varchar(500),
    system_role boolean not null default true,
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table app_user (
    id bigint generated by default as identity primary key,
    username varchar(80) not null unique,
    email varchar(255) not null unique,
    password_hash varchar(255) not null,
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index uq_app_user_username_lower on app_user (lower(username));
create unique index uq_app_user_email_lower on app_user (lower(email));

create table user_role (
    user_id bigint not null references app_user(id) on delete cascade,
    role_id bigint not null references role(id),
    assigned_at timestamptz not null default now(),
    assigned_by bigint references app_user(id),
    primary key (user_id, role_id)
);

insert into role (code, name, description, system_role, active)
values ('INVENTORY_VIEWER', 'Inventory Viewer', 'Default role for newly registered users.', true, true);
