create extension if not exists pg_trgm;

create table role (
    id bigint generated by default as identity primary key,
    code varchar(80) not null,
    name varchar(120) not null,
    description varchar(500),
    system_role boolean not null default true,
    active boolean not null default true,
    version bigint not null default 0,
    permissions text[] not null default '{}'::text[],
    created_by varchar(255) not null default 'SYSTEM',
    created_date timestamptz not null default now(),
    last_modified_by varchar(255) not null default 'SYSTEM',
    last_modified_date timestamptz not null default now(),
    constraint ck_role_code_not_blank check (btrim(code) <> ''),
    constraint ck_role_name_not_blank check (btrim(name) <> ''),
    constraint ck_role_permissions_without_nulls check (array_position(permissions, null) is null)
);

create unique index uq_role_code_lower on role (lower(code));
create index idx_role_active_code on role (active, code, id);
create index idx_role_code_trgm on role using gin (lower(code) gin_trgm_ops);
create index idx_role_name_trgm on role using gin (lower(name) gin_trgm_ops);

create table app_user (
    id bigint generated by default as identity primary key,
    username varchar(80) not null,
    email varchar(255) not null,
    oidc_issuer varchar(500),
    oidc_subject varchar(255),
    active boolean not null default true,
    version bigint not null default 0,
    created_by varchar(255) not null default 'SYSTEM',
    created_date timestamptz not null default now(),
    last_modified_by varchar(255) not null default 'SYSTEM',
    last_modified_date timestamptz not null default now(),
    constraint ck_app_user_username_not_blank check (btrim(username) <> ''),
    constraint ck_app_user_email_not_blank check (btrim(email) <> ''),
    constraint ck_app_user_oidc_identity_complete check (
        (oidc_issuer is null and oidc_subject is null)
        or (oidc_issuer is not null and oidc_subject is not null)
    )
);

create unique index uq_app_user_username_lower on app_user (lower(username));
create unique index uq_app_user_email_lower on app_user (lower(email));
create unique index uq_app_user_oidc_identity on app_user (oidc_issuer, oidc_subject)
    where oidc_issuer is not null;
create index idx_app_user_active_username on app_user (active, username, id);
create index idx_app_user_username_trgm on app_user using gin (lower(username) gin_trgm_ops);
create index idx_app_user_email_trgm on app_user using gin (lower(email) gin_trgm_ops);

create table user_role (
    user_id bigint not null,
    role_id bigint not null,
    assigned_at timestamptz not null default now(),
    assigned_by bigint,
    primary key (user_id, role_id),
    constraint fk_user_role_user foreign key (user_id) references app_user(id) on delete cascade,
    constraint fk_user_role_role foreign key (role_id) references role(id) on delete restrict,
    constraint fk_user_role_assigned_by foreign key (assigned_by) references app_user(id) on delete set null
);

create index idx_user_role_role_id on user_role (role_id, user_id);
create index idx_user_role_assigned_by on user_role (assigned_by) where assigned_by is not null;
