create table category (
    id bigint generated by default as identity primary key,
    name varchar(120) not null,
    description varchar(500),
    active boolean not null default true,
    version bigint not null default 0,
    created_by varchar(255) not null default 'SYSTEM',
    created_date timestamptz not null default now(),
    last_modified_by varchar(255) not null default 'SYSTEM',
    last_modified_date timestamptz not null default now(),
    constraint ck_category_name_not_blank check (btrim(name) <> '')
);

create unique index uq_category_name_lower on category (lower(name));
create index idx_category_active_name on category (active, name, id);
create index idx_category_name_trgm on category using gin (lower(name) gin_trgm_ops);

create table supplier (
    id bigint generated by default as identity primary key,
    name varchar(160) not null,
    contact_name varchar(160),
    email varchar(255),
    phone varchar(80),
    active boolean not null default true,
    version bigint not null default 0,
    created_by varchar(255) not null default 'SYSTEM',
    created_date timestamptz not null default now(),
    last_modified_by varchar(255) not null default 'SYSTEM',
    last_modified_date timestamptz not null default now(),
    constraint ck_supplier_name_not_blank check (btrim(name) <> '')
);

create index idx_supplier_active_name on supplier (active, name, id);
create index idx_supplier_name_trgm on supplier using gin (lower(name) gin_trgm_ops);
create index idx_supplier_contact_name_trgm on supplier using gin (lower(contact_name) gin_trgm_ops);

create table product (
    id bigint generated by default as identity primary key,
    sku varchar(80) not null,
    name varchar(160) not null,
    description varchar(1000),
    unit_price numeric(12, 2) not null,
    quantity_on_hand integer not null,
    minimum_stock integer not null,
    active boolean not null default true,
    category_id bigint not null,
    supplier_id bigint,
    version bigint not null default 0,
    created_by varchar(255) not null default 'SYSTEM',
    created_date timestamptz not null default now(),
    last_modified_by varchar(255) not null default 'SYSTEM',
    last_modified_date timestamptz not null default now(),
    constraint fk_product_category foreign key (category_id) references category(id) on delete restrict,
    constraint fk_product_supplier foreign key (supplier_id) references supplier(id) on delete restrict,
    constraint ck_product_sku_not_blank check (btrim(sku) <> ''),
    constraint ck_product_name_not_blank check (btrim(name) <> ''),
    constraint ck_product_unit_price_non_negative check (unit_price >= 0),
    constraint ck_product_quantity_non_negative check (quantity_on_hand >= 0),
    constraint ck_product_minimum_stock_non_negative check (minimum_stock >= 0)
);

create unique index uq_product_sku_lower on product (lower(sku));
create unique index uq_product_active_name_lower on product (lower(name)) where active;
create index idx_product_active_sku on product (active, sku, id);
create index idx_product_category_id on product (category_id, id);
create index idx_product_supplier_id on product (supplier_id, id) where supplier_id is not null;
create index idx_product_low_stock on product (sku, id)
    where active and quantity_on_hand <= minimum_stock;
create index idx_product_sku_trgm on product using gin (lower(sku) gin_trgm_ops);
create index idx_product_name_trgm on product using gin (lower(name) gin_trgm_ops);

create table stock_movement (
    id bigint generated by default as identity primary key,
    product_id bigint not null,
    user_id bigint,
    movement_type varchar(40) not null,
    quantity_delta integer not null,
    reason varchar(500),
    created_by varchar(255) not null default 'SYSTEM',
    created_date timestamptz not null default now(),
    last_modified_by varchar(255) not null default 'SYSTEM',
    last_modified_date timestamptz not null default now(),
    constraint fk_stock_movement_product foreign key (product_id) references product(id) on delete restrict,
    constraint fk_stock_movement_user foreign key (user_id) references app_user(id) on delete restrict,
    constraint ck_stock_movement_quantity_non_zero check (quantity_delta <> 0),
    constraint ck_stock_movement_type check (movement_type in (
        'PURCHASE',
        'SALE',
        'RETURN_IN',
        'RETURN_OUT',
        'ADJUSTMENT_IN',
        'ADJUSTMENT_OUT',
        'INITIAL_STOCK',
        'DAMAGED',
        'LOST'
    ))
);

create index idx_stock_movement_created on stock_movement (created_date desc, id desc);
create index idx_stock_movement_product_created on stock_movement (product_id, created_date desc, id desc);
create index idx_stock_movement_user_created on stock_movement (user_id, created_date desc, id desc)
    where user_id is not null;
create index idx_stock_movement_type_created on stock_movement (movement_type, created_date desc, id desc);
