create table category (
    id bigint generated by default as identity primary key,
    name varchar(120) not null unique,
    description varchar(500),
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index uq_category_name_lower on category (lower(name));

create table supplier (
    id bigint generated by default as identity primary key,
    name varchar(160) not null,
    contact_name varchar(160),
    email varchar(255),
    phone varchar(80),
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table product (
    id bigint generated by default as identity primary key,
    sku varchar(80) not null unique,
    name varchar(160) not null,
    description varchar(1000),
    unit_price numeric(12, 2) not null,
    quantity_on_hand integer not null,
    minimum_stock integer not null,
    active boolean not null default true,
    category_id bigint not null references category(id),
    supplier_id bigint references supplier(id),
    version bigint not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint ck_product_unit_price_non_negative check (unit_price >= 0),
    constraint ck_product_quantity_non_negative check (quantity_on_hand >= 0),
    constraint ck_product_minimum_stock_non_negative check (minimum_stock >= 0)
);

create unique index uq_product_sku_lower on product (lower(sku));
create unique index uq_product_active_name_lower on product (lower(name)) where active = true;

create table stock_movement (
    id bigint generated by default as identity primary key,
    product_id bigint not null references product(id),
    user_id bigint references app_user(id),
    movement_type varchar(40) not null,
    quantity_delta integer not null,
    reason varchar(500),
    created_at timestamptz not null default now(),
    constraint ck_stock_movement_quantity_non_zero check (quantity_delta <> 0)
);

insert into role (code, name, description, system_role, active)
values
    ('INVENTORY_MANAGER', 'Inventory Manager', 'Can manage catalog records.', true, true),
    ('SYSTEM_ADMINISTRATOR', 'System Administrator', 'Can administer all application areas.', true, true)
on conflict (code) do nothing;

insert into category (name, description, active)
values
    ('General', 'Default product category.', true),
    ('Hardware', 'Physical inventory and equipment.', true)
on conflict do nothing;

insert into supplier (name, contact_name, email, phone, active)
values
    ('Acme Supply', 'Acme Desk', 'orders@acme.example', '555-0100', true),
    ('Internal Stock', null, null, null, true);
