alter table role
    add column version bigint not null default 0;

create table resource (
    id bigint generated by default as identity primary key,
    code varchar(80) not null unique,
    name varchar(120) not null,
    description text,
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint chk_resource_code_not_blank check (length(trim(code)) > 0),
    constraint chk_resource_name_not_blank check (length(trim(name)) > 0)
);

create table action (
    id bigint generated by default as identity primary key,
    code varchar(80) not null unique,
    name varchar(120) not null,
    description text,
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint chk_action_code_not_blank check (length(trim(code)) > 0),
    constraint chk_action_name_not_blank check (length(trim(name)) > 0)
);

create table permission (
    id bigint generated by default as identity primary key,
    resource_id bigint not null references resource(id) on delete restrict,
    action_id bigint not null references action(id) on delete restrict,
    description text,
    active boolean not null default true,
    version bigint not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uk_permission_resource_action unique (resource_id, action_id)
);

create table role_permission (
    role_id bigint not null references role(id) on delete restrict,
    permission_id bigint not null references permission(id) on delete restrict,
    granted_at timestamptz not null default now(),
    granted_by bigint references app_user(id),
    primary key (role_id, permission_id)
);

create index idx_role_permission_permission_id on role_permission(permission_id);
create index idx_permission_resource_id on permission(resource_id);
create index idx_permission_action_id on permission(action_id);

insert into resource (code, name, description)
values
    ('PRODUCT', 'Product', 'Inventory product records.'),
    ('CATEGORY', 'Category', 'Product category records.'),
    ('SUPPLIER', 'Supplier', 'Supplier records.'),
    ('STOCK_MOVEMENT', 'Stock Movement', 'Inventory stock movement ledger.'),
    ('USER', 'User', 'Application user accounts.'),
    ('ROLE', 'Role', 'Role records.'),
    ('PERMISSION', 'Permission', 'Permission records.'),
    ('REPORT', 'Report', 'Inventory reports and exports.');

insert into action (code, name, description)
values
    ('CREATE', 'Create', 'Create records.'),
    ('READ', 'Read', 'Read records.'),
    ('UPDATE', 'Update', 'Update records.'),
    ('DELETE', 'Delete', 'Delete records.'),
    ('ASSIGN', 'Assign', 'Assign roles or permissions.'),
    ('EXPORT', 'Export', 'Export records or reports.');

insert into permission (resource_id, action_id, description)
select resource.id, action.id, resource.code || ':' || action.code
from resource
cross join action
where
    (resource.code in ('PRODUCT', 'CATEGORY', 'SUPPLIER') and action.code in ('CREATE', 'READ', 'UPDATE', 'DELETE', 'EXPORT'))
    or (resource.code = 'STOCK_MOVEMENT' and action.code in ('CREATE', 'READ', 'EXPORT'))
    or (resource.code in ('USER', 'ROLE', 'PERMISSION') and action.code in ('CREATE', 'READ', 'UPDATE', 'DELETE', 'ASSIGN'))
    or (resource.code = 'REPORT' and action.code in ('READ', 'EXPORT'));

insert into role_permission (role_id, permission_id)
select role.id, permission.id
from role
cross join permission
where role.code = 'SYSTEM_ADMINISTRATOR';

insert into role_permission (role_id, permission_id)
select role.id, permission.id
from role
join permission on true
join resource on resource.id = permission.resource_id
join action on action.id = permission.action_id
where role.code = 'INVENTORY_MANAGER'
  and (
      (resource.code in ('PRODUCT', 'CATEGORY', 'SUPPLIER') and action.code in ('CREATE', 'READ', 'UPDATE', 'DELETE', 'EXPORT'))
      or (resource.code = 'STOCK_MOVEMENT' and action.code in ('CREATE', 'READ', 'EXPORT'))
      or (resource.code = 'REPORT' and action.code in ('READ', 'EXPORT'))
  );

insert into role_permission (role_id, permission_id)
select role.id, permission.id
from role
join permission on true
join resource on resource.id = permission.resource_id
join action on action.id = permission.action_id
where role.code = 'WAREHOUSE_OPERATOR'
  and (
      (resource.code = 'PRODUCT' and action.code = 'READ')
      or (resource.code = 'CATEGORY' and action.code = 'READ')
      or (resource.code = 'SUPPLIER' and action.code = 'READ')
      or (resource.code = 'STOCK_MOVEMENT' and action.code in ('CREATE', 'READ'))
  );

insert into role_permission (role_id, permission_id)
select role.id, permission.id
from role
join permission on true
join resource on resource.id = permission.resource_id
join action on action.id = permission.action_id
where role.code = 'INVENTORY_VIEWER'
  and (
      (resource.code in ('PRODUCT', 'CATEGORY', 'SUPPLIER', 'STOCK_MOVEMENT', 'REPORT') and action.code = 'READ')
  );
